[phases.setup]
nixPkgs = ['python310']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'python webhook_service.py'